practice_app/sanberk_PS.txt

A `practice_app` folder is created and a file is added for trial purposes as stated in PS.

Trial commit 

---

practice_app/berat_PS.txt

a file named "berat_PS.txt"is added for trial purposes as stated in PS.

trial commit for PS

---

practice_app/main_app/users/views.py

Login problem resolved

---

practice_app/main_app/post/models.py
practice_app/main_app/post/templates/post/home.html
practice_app/main_app/post/templates/post/post_detail.html
practice_app/main_app/post/templates/post/user_posts.html
practice_app/main_app/post/urls.py
practice_app/main_app/post/views.py

I have implemented the like functionality as mentioned https://github.com/bounswe/bounswe2022group4/issues/144. Users are able to like(upvote) a post now.

like functionality implemented

---

practice_app/main_app/post/templates/post/home.html
practice_app/main_app/post/urls.py
practice_app/main_app/post/views.py

I impelemented API for likes with GET and POST method. I used GET method to get number of total likes of a post. Also likes a post for a user using API.
I created /like/count/<int:pk>, /like/post/
/like/count/<int:pk> => GET request: view total likes
/like/post/ => POST request: likes a post for a user

like api implemented

---

practice_app/main_app/post/admin.py
practice_app/main_app/post/models.py
practice_app/main_app/post/templates/post/comment_form.html
practice_app/main_app/post/templates/post/home.html
practice_app/main_app/post/templates/post/post_detail.html
practice_app/main_app/post/templates/post/user_posts.html
practice_app/main_app/post/urls.py
practice_app/main_app/post/views.py

comment system implemented

---

practice_app/main_app/post/admin.py
practice_app/main_app/users/views.py

bugs about api keys is fixed

---

practice_app/main_app/post/templates/post/base.html
practice_app/main_app/post/templates/post/home.html
practice_app/main_app/post/templates/post/post_detail.html
practice_app/main_app/post/urls.py
practice_app/main_app/users/urls.py
practice_app/main_app/users/views.py

With GET api which is **base_url/all-profiles/** , get all users profile infos
With POST api which is **base_url/edit-profile-api/** , update profile info of user whose username is in POST body.

Profile get and post apis

---

practice_app/main_app/main_app/settings.py
practice_app/main_app/post/context_processors.py
practice_app/main_app/post/models.py
practice_app/main_app/post/serializers.py
practice_app/main_app/post/templates/post/category_form_two.html
practice_app/main_app/post/views.py

* Category models and views are moderated.
* Extra context processor added.
* Category addition success-error messages organized.

Category models-views revisoned

---

practice_app/main_app/post/templates/post/base.html
practice_app/main_app/post/templates/post/new_face.html
practice_app/main_app/users/urls.py
practice_app/main_app/users/views.py

Added external api for seeing new faces.
Taking inspire from them to make new things on yourself will be good for everyone.

Added extermal api for new faces

---

practice_app/main_app/post/tests.py

**Unit tests are added.** Following functions are tested: 
- Category object creation method.
- Category API GET method.
- Category API POST method.

Category and Category API Unit Tests are Added

---

practice_app/main_app/post/views.py
practice_app/main_app/users/views.py

static IPs changed to dynamic ones

---

practice_app/main_app/main_app/settings.py
practice_app/main_app/post/admin.py
practice_app/main_app/users/tests/test_views.py
practice_app/main_app/users/urls.py

Unit tests implemented for profile

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/pages/SignInPage/SignInPage.css
heka-front/src/pages/SignInPage/SignInPage.js

I implemented  a login page. Users and doctors are able to log in by providing e-mail and passwords.  I checked if the enterd e-mail address is valid or not. Firstly, I used regex to contol validation of e-mail address but I changed regex to using "validator" package to be more consistent. If users does not enter valid e-mail, they encounter a error message "Please enter a valid email address".  This message does not get lost untill users enter any character.  If users have not registered yet, I added a link to registration page under "Not Registered Yet" title. 
⚠️ Please note that this version does not include backend connection. I will implement backend connection after backend team provide required API's.
➡️ You can see detail information related issue #259 .

Implementing login page using e-mail and password without backend connection

---

heka-front/src/pages/SignInPage/SignInPage.css
heka-front/src/pages/SignInPage/SignInPage.js

Login Page affected all other pages in terms of color, stye, size, front etc. I solved bug using extra div component at the top of login page. Therefore, it affects only login pages not affecting other pages.  I also configured login page size considering navbar. 
It seems okey now.

Bug: Login page affects all other pages in terms of color,style etc. 

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/api/ApiInstance.js
heka-front/src/api/Backend/Backend.js
heka-front/src/api/index.js

I have created a base for backend connection in frontend. I have implemented postLogin and postRegister functions which handles post requests with necessary parameters.

feat: created a base for backend connection

---

heka-front/src/pages/SignInPage/SignInPage.css
heka-front/src/pages/SignInPage/SignInPage.js
package-lock.json

**Improvements on previous version:**
* I redesigned our login page to be more user friendly. 
* I added backend connection with given API.  
* I also added error message "invalid e-mail or password" if  users enter wrong e-mail or password.
➡️  For more details #259

Login page is connected to backend now

---

heka-front/src/pages/SignInPage/SignInPage.css
heka-front/src/pages/SignInPage/SignInPage.js

I have improved ui of the login page.
1) I implement animation for buttons
2) I made login page responsive
3) I have solved some bugs in css

Heka front login UI improvement

---

heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/SignUpPage/SignUpPage.js

I have a prettier  so this is the reason of all style changes

Sign-Up was added

---

.gitignore
backend/heka/heka/settings.py
backend/heka/heka/urls.py
backend/heka/requirements.txt
backend/heka/users/views.py

Migration from *rest-framework-swagger* to *drf-yasg* was completed. Please review it.

Backend: Migrates from rest-framework-swagger to drf-yasg

---

heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/HomePage/HomePage.css
heka-front/src/pages/HomePage/HomePage.js

Implemented some text effect on texts and change the font family in the homepage.

feat: UI improvements in homepage

---

.github/workflows/backend.yml
.gitignore
backend/heka/Dockerfile
backend/heka/docker-compose.yml
backend/heka/heka/settings.py
backend/heka/requirements.txt

Changes about the deployment should be applied to the heka-backend branch first. Then they will be merged with the main. Otherwise Github Actions does not operates.
* Add Dockerfile and docker-compose.yml #249
* Add Github Actions workflow #250

Heka backend deployment

---

heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/tests/HomePage.test.js

I have implemented test cases for the HomePage. I also add data test id to the button components in Post component in order to test them.
For more details, you can look at https://github.com/bounswe/bounswe2022group4/issues/285.

feat: HomePage test cases

---

heka-front/src/pages/SignUpPage/SignUpPage.css
heka-front/src/pages/SignUpPage/SignUpPage.js

@umutdenizsenerr pushing for the last updates

Sign-up page update

---

backend/heka/users/tests.py
backend/heka/users/urls.py
backend/heka/users/views.py

Unit tests for register and login functionalities were completed. Please review my code.

Backend: Implement unit tests for register and login functionalities.

---

heka-front/src/App.js
heka-front/src/components/Navbar/Navbar.js
heka-front/src/pages/SignInPage/SignInPage.js

I stored login information of the user in global state and using the variable in navigation bar. I hide profile page if user not logged in and hide sign in and sign up button and show sign out button if user logged in.

Store Login Info in Global State and Using In Navigation Bar

---

heka-front/src/pages/ProfilePage/ProfilePage.js
heka-front/src/pages/ProfilePage/profilePage.css

Profile page of users is added for Milestone I presentation. The customer is now able to see what the static user profile pages will look like with this update. A review is needed. @umutdenizsenerr

Frontend - Profile page is added

---

.githbub/workflows/front.yml
.github/workflows/front.yml
heka-front/Dockerfile
heka-front/docker-compose.yml
heka-front/src/api/ApiInstance.js

Heka front

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I configured Evaluation of Tools section

Group review tools addition

---

.github/workflows/front.yml

It automatically deploy changes in the heka-front branch. The changes are visible 3.72.25.175:3000 address.

Add EC2 deployment to Github Actions

---

.github/workflows/backend.yml
backend/heka/heka/settings.py
backend/heka/heka/urls.py
backend/heka/users/apps.py
backend/heka/users/models.py
backend/heka/users/serializers.py
backend/heka/users/tests.py
backend/heka/users/views.py

The authentication mechanism now uses Token Authentication provided by the Django REST framework.

Backend: Token Authentication provided by Django REST framework implemented.

---

heka-front/src/App.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/HomePage/HomePage.js

I make username private to the unauthorized users. User should be able to view other user's username only if he/she login to the web application.
* I get login information in home page
* I hide username information of other users from unauthorized user

Frontend: Username Privacy

---

heka-front/src/pages/ForgotPassword/ForgotPassword.css
heka-front/src/pages/ForgotPassword/ForgotPassword.js

I implemented  two step of changing password as follows:
Firsty, if a user forgot his/her password, he/she can click "forgot password?" link and then the user enter e-mail address associated with Heka account. After that, our system will send a email with verification code and a  form is created for verification code. The user should enter verification code corrrectly to be able to change his/her password. If user enters correct verification code, new form is created to determine new password. However, this version does not contain determining new password part. That will be implemented another pull request. I think that this version should be merged to give idea to other members of the team.

Frontend: Validation for  Forgot Password Feature

---

backend/heka/docker-compose.yml
backend/heka/users/models.py
backend/heka/users/serializers.py
backend/heka/users/urls.py
backend/heka/users/views.py

It implements /api/user/profilepage/username endpoint and add username to the authentication endpoints. It also adds profile picture to the User model.

Heka backend profilepage

---

backend/heka/posts/urls.py
backend/heka/posts/views.py

It implements /post/list-posts  endpoint.

Backend: Lists all posts

---

backend/heka/chat/serializers.py
backend/heka/chat/urls.py
backend/heka/chat/views.py

I added an endpoint to fetch a users messaged users list.

Added fetch messaged users endpoint

---

backend/heka/posts/models.py
backend/heka/posts/urls.py
backend/heka/posts/views.py
backend/heka/users/models.py
backend/heka/users/views.py

This implements some different functionalities as explained below.
- Upvote and downvote functionalities of Post and Comment models implemented.
- Users were assumed to be logged in just after the registration. They have to log in after the registration from now on.
- Image fields for Post and Comment added.
- Fetching of comments of a post implemented. It returns all the comments of a post sorted by creation time.
- Fetching of posts was allowed for only authenticated users. Guest users are also allowed to display posts now.

Backend: Implements some functionalities and handles inconsistencies.

---

backend/heka/posts/permissions.py
backend/heka/posts/views.py

It implements the necessary permission handling for update and delete functionalities of Post and Comment models.

Backend: Fixes the permission requirements for update and delete functionalities of Post and Comment models.

---

heka-front/package-lock.json
heka-front/src/components/SideBar/SideBar.css
heka-front/src/components/SideBar/SideBar.js
heka-front/src/pages/HomePage/HomePage.css
heka-front/src/pages/HomePage/HomePage.js

**About feature:**
I implemented a category sidebar in homepage. A user can show categories thanks to sidebar. After category feature is implemented by backend team, I will connect categories with posts.  Thanks to that connection, users can show all post under a category clicking related category.
Since backend did not provide categories feature , I researched some categories of medicine and then added them to sidebar.
➡️ For more details, you can look at #372 
**Implementation details:**
-  I used a different component for category. I created css and js files for category sidebar.
-  I collected that files under components folders creating new folder named "SideBar".
-  I also changed size of posts in home page to locate sidebar to homepage.  I set widths  of components using percentage …

Frontend:  Category Section 

---

heka-front/src/App.js
heka-front/src/components/SideBar/SideBar.css
heka-front/src/components/SideBar/SideBar.js
heka-front/src/pages/ForgotPassword/ForgotPassword.css
heka-front/src/pages/ForgotPassword/ForgotPassword.js
heka-front/src/pages/HomePage/HomePage.css
heka-front/src/pages/SignInPage/SignInPage.js

**About feature:**
I implemented forgot password functionality for our application. If users forgot their passwords, they are able to change their password. All steps that users should follow while reset their passwords can be describes as:
1. Users should clik on "change password" in top on sign-in screen.
2. Users should provide e-mail addresses assosiated with Heka account.
3. A email is sent for verification code. Users should enter that verification code and then click "Verify" button.
4. If verfication code is correct, users can determine their new passwords by confirming them.
Since backend did not provide forgot-password feature  yet, I did not connect that functioanlity with backend.
➡️ For more details, you can look at #347 
**Implementation details:**
-  I used same page for …

Frontend: Forgot Password 

---

backend/heka/users/serializers.py
backend/heka/users/views.py

It implements edit profile page endpoint.

Backend: Add edit profile page endpoint

---

backend/heka/posts/models.py
backend/heka/posts/serializers.py
backend/heka/posts/views.py

It modifies the response bodies for APIs handling listing and updating posts and comments.
* Listing and updating comments now return the body, creator username, the boolean value of creator being health expert or not, last update date, number of upvotes, and number of downvotes of comments.
* Listing and updating posts now return category, title, body, slug, image attached, location, creator username, the boolean value of creator being health expert or not, last update date, number of upvotes, and number of downvotes of posts.

Backend: Modifies response bodies of APIs handling listing and updating of posts and comments.

---

heka-front/src/App.js
heka-front/src/api/ApiInstance.js
heka-front/src/api/Backend/Backend.js
heka-front/src/components/CreatePost/CreatePost.js
heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/HomePage/HomePage.js
heka-front/src/pages/SignInPage/SignInPage.js
heka-front/src/pages/SignUpPage/SignUpPage.js

I have created Post structure before with delete button, create post button and PostBox structure in the home page. Now i have connected these functionalities to the backend. I have implemented the structure that allows:
* User is able to create post by providing title and body (i will add other fields when backend updated)
* User is able to view created posts in the home page
* User is able to delete its own post

Frontend: Post Structure Backend Connection

---

backend/heka/posts/models.py
backend/heka/posts/serializers.py
backend/heka/posts/views.py

Last updated time of posts and comments are now updated only upon update of posts and comments, not other functionalities such as upvote or downvote.

Backend: Handles some inconsistencies related to last update time of posts and comments.

---

heka-front/src/api/Backend/Backend.js
heka-front/src/components/Comment/Comment.js
heka-front/src/components/CommentBox/CommentBox.js
heka-front/src/components/CreateComment/CreateComment.js
heka-front/src/components/Post/Post.js

I have created comment structure before with create comment button and CommentBox structure in the home page. Now i have connected these functionalities to the backend. I have implemented the structure that allows:
* User is able to create comment by providing body
* User is able to view created comments under the post
* User is able to upvote a comment
* User is able to downvote a comment

Frontend: Comment Backend Connection

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/api/Backend/Backend.js
heka-front/src/components/Comment/Comment.js
heka-front/src/components/CommentBox/CommentBox.js
heka-front/src/components/CreateComment/CreateComment.js
heka-front/src/components/CreatePost/CreatePost.js
heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/SignUpPage/SignUpPage.js

In the Create Post structure there is a field that user can upload image related to the post. In order to make this feature light weight we have decided to post images as base64 text to the database and getting them as base64 image and render them.
* I have converted image files to base 64 text by using react-file-image-to-base64 library
* I have make post request with image data when creating the post
* I have make get request with image data
* I have rendered base64 text as image in Post by using image component in react

Frontend: Create Post Image Uploading and Post Base 64 Image Rendering

---

backend/heka/chat/views.py
backend/heka/heka/settings.py
backend/heka/users/models.py
backend/heka/users/urls.py
backend/heka/users/views.py

I implemented the forget password functionality for the backend API. From now on user can update their password. 
Two endpoints implemented, 
/api/user/forget_password : user's email is given as input. an email sent to the given mail address which contains the password reset code  
/api/user/reset_password : user gives it's code which she get from the email, and new password. and user's password will be updated.

Heka backend forget password

---

heka-front/src/api/Backend/Backend.js
heka-front/src/components/CommentBox/CommentBox.js
heka-front/src/components/Post/Post.js

I have implemented the backend connection for upvoting and downvoting the posts.
* I have created api connection for upvote and downvote endpoints
* I have implemented functions for handling upvote and downvote
* I re-render page after each update in upvote and downvote

Frontend: Backend Connection For Vote Post

---

heka-front/src/api/Backend/Backend.js
heka-front/src/components/Comment/Comment.js
heka-front/src/components/CommentBox/CommentBox.js
heka-front/src/components/Post/Post.js

I have created Comment structure before with delete button. Now i have connected it to backend, in order to make delete button functional. Also, user can only delete its own posts.
* I have added backend end point for delete comment in frontend structure as a async function.
* I have used authentication token for the delete comment request
* I have used useEffect hook in order to re-render page in order to view updated Comment structure

Frontend: Delete Comment Backend Connection

---

heka-front/src/components/SideBar/SideBar.css
heka-front/src/components/SideBar/SideBar.js
heka-front/src/pages/SignUpPage/SignUpPage.css
heka-front/src/pages/SignUpPage/SignUpPage.js

We relaized that doctor sign-up button is affected by other buttons due to name conflicts. I found the reason of that bug and I made improvements doctor sign-up page to resolve name conflicts with other pages.  I also changed size of category side bar. There is allignment problem between post and sidebar. The reason of that problem is also usage of same name for containers.
Now, all conflicts are resolved and size of button is appropriate  for our sign-up form. Side bar is alligned accordng to start position of first post.
➡️ For more details, you can look at #413 
@umutdenizsenerr 
04.12.2022 23.59

Frontend Bug: Doctor Sign-Up Button Size Exceeds Form Container

---

heka-front/src/App.js
heka-front/src/api/Backend/Backend.js
heka-front/src/components/Comment/Comment.js
heka-front/src/components/CommentBox/CommentBox.js
heka-front/src/components/EditPost/EditPost.js
heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/HomePage/HomePage.js
heka-front/src/pages/SignInPage/SignInPage.js

I have implemented edit functionality for the posts. Users are able to edit only its own post. 
* I have created an EditPost Modal which is similar to CreatePost Modal
* I have implemented the structure that pre-fill values of EditPost Modal with the values of related post
* I have connected backend endpoint into EditPost Modal
* I have made this functionality available only for post owner
* I  re-render posts after every update
Now: 
* When user click to the edit button, he/she can view a modal that has pre-filled fields with old data and he/she scan change these fields with the ones he/she desire.
* If user does not provide image or location these fields will remain same.
* After updating the post user can view updated post.

Frontend: Edit Post

---

backend/heka/posts/views.py

This makes the creator field of posts and comments immutable.

Backend: Fixes tiny bugs.

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/components/CommentBox/CommentBox.js
heka-front/src/components/CreatePost/CreatePost.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/components/SearchBar/SearchBar.css
heka-front/src/components/SearchBar/SearchBar.js
heka-front/src/pages/HomePage/HomePage.js

While getting posts from database, it takes some time and for the better user experience i have implemented a loading state structure that will show loading spin while loading.
* I have implement a useState hook for holding isLoading
* I have rendered loading spin while isLoading

Frontend: Loading States

---

heka-front/src/components/Chat/MessageChat.js
heka-front/src/pages/HomePage/HomePage.js
heka-front/src/pages/ProfilePage/ProfilePage.js

Heka front chat UI update

---

backend/heka/users/tests.py
backend/heka/users/views.py

It adds tests for the GET and PUT endpoints of the ProfilePage. I discovered that it was unnecessary to get user from the database. Because Django already authenticates the user and appends it to the request. We can easily access it with "request.user" .

Backend: profilepage tests

---

backend/heka/posts/urls.py
backend/heka/posts/views.py

It implements fetch comment functionality.

Backend: Implements fetch comment.

---

heka-front/package-lock.json
heka-front/src/App.js
heka-front/src/components/EditProfile/EditProfile.js
heka-front/src/components/Navbar/Navbar.js
heka-front/src/pages/ProfilePage/ProfilePage.js

Static design of edit profile page is completed.
Users now can link to user profile edit pages and and they have several input fields and a button for submitting.

Frontend: Design of Static Edit Profile Page

---

heka-front/package-lock.json
heka-front/src/components/Post/Post.js
heka-front/src/tests/Post.test.js
heka-front/src/tests/PostBox.test.js

I have finished implementation of the Post Structure. I have implemented create post, delete post, edit post, upvote post, downvote post functionalities. Now i have written unit test cases for the home page by using react testing library.
* I have prepared test case scenarios.
* I have implemented these scenarios in web application.

Frontend: Unit Tests for Posts

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/tests/ForgetPassword.test.js

I implemented search, forget password and categories functionalities for our web application.  Now, I wrote some unit tests for them. I implemented my test in a way that all possible cases are covered.
-  I tested whether Email input is placed on forget password page
-  I tested whether Email input takes entered e-mail correctly
-  I tested behavior of our application when non-valid Email input is placed on   forget password page
-  I tested behavior of our application when valid Email input is placed on forget password  page
-   I tested whether search bar takes input correctly
-    I tested whether  search bar is placed on homepage
-    I tested whether  category side bar is placed on homepage correctly
-  I tested whether category side bar works correctly
➡️ For more details, you can …

Frontend: Unit Test for Forget Password, Search and Categories Functionalities

---

heka-front/src/App.js
heka-front/src/api/Backend/Backend.js
heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/HomePage/HomePage.js
heka-front/src/pages/PostPage/PostPage.css
heka-front/src/pages/PostPage/PostPage.js

I have completed the task of creating a single post page in our project. This page is a React component that displays the post's title, body, and any other relevant information. I have also added the new page to the project's React Router configuration and retrieved the necessary data for the page from the backend of the application. I have also added any necessary CSS styles to the single post page to ensure that it is visually appealing and easy to read. I have tested the single post page and it is functioning correctly and displaying the post's information as expected.

Frontend: Single Post Page and URL

---

heka-front/src/App.js
heka-front/src/api/Backend/Backend.js
heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/components/ReportPost/ReportPost.js
heka-front/src/pages/HomePage/HomePage.js
heka-front/src/pages/PostPage/PostPage.css
heka-front/src/pages/PostPage/PostPage.js

* I created a new component called ReportModal to handle the report submission form.
* I imported the Modal component from the library and added it to the ReportModal component.
* Inside the Modal component, I added a form with a text field for the user to enter a description of the issue with the post and any relevant details.
* I used the useState and useEffect hooks to bind the form to the component's state, and used the onSubmit event to handle the form submission.
* I added a callback function to the Post component that opens the ReportModal when the "Report Post" button is clicked, and passed the necessary props down to the ReportModal component.

Frontend: Report Post

---

backend/heka/heka/settings.py
backend/heka/heka/urls.py
backend/heka/search/admin.py
backend/heka/search/apps.py
backend/heka/search/models.py
backend/heka/search/tests.py
backend/heka/search/views.py
backend/heka/textSearch/admin.py
backend/heka/textSearch/apps.py
backend/heka/textSearch/models.py
backend/heka/textSearch/tests.py
backend/heka/textSearch/urls.py
backend/heka/textSearch/views.py

Initialized the search application. Configured the urls and settings. Finally added the search user functionality. From now on one can search a user by supplying a username.
Developed endpoint:
/api/search/user?query={input}

Backend: Search Application - Initialized the application and added the user search functionality

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/App.js
heka-front/src/components/Post/Post.js
heka-front/src/components/TextAnnotation/TextAnnotation.js

I've implemented the text annotation feature for our medical experience sharing platform. This feature allows users to highlight and annotate specific text within their medical experiences, and save the annotation for future reference.
I've included the necessary UI elements and written the logic to handle user interaction with the annotation feature. I've also tested the feature to ensure it is functioning as intended, and documented it for other developers to understand.

Frontend: Text Annotation Structure

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/App.js
heka-front/src/components/Post/Post.js
heka-front/src/components/TextAnnotation/TextAnnotation.js
heka-front/src/pages/ProfilePage/ProfilePage.js

This pull request resolves an issue with the profile page not being properly connected to the backend. Users were unable to view or edit their personal information on the profile page, which hindered their ability to fully utilize the platform and share their medical experiences.
To fix this issue, I modified the frontend code to make a request to the appropriate backend API endpoint and handle the response. I also tested the profile page to ensure that it was properly connected to the backend and functioning correctly.
This change should improve the user experience on the platform by allowing users to view and edit their personal information on the profile page.

Frontend: Profile Page Backend Connection

---

backend/heka/docker-compose.yml
backend/heka/textSearch/urls.py
backend/heka/textSearch/views.py

I have added the post search functionality, from now on users can search posts with the below service. There are two input parameters. query parameter is used to get input from the user and generate a search results according to given query. count parameter was developed to limit the number of posts in the response returned from the API.
Developed endpoint:
/api/search/post?query={input}&count={input}
Other than that, Users search functionality improved. I have added the error conditions, number of users on the response and id values of the users.

Backend: Search Application - Added the post search functionality

---

backend/heka/annotations/admin.py
backend/heka/annotations/apps.py
backend/heka/annotations/models.py
backend/heka/annotations/serializers.py
backend/heka/annotations/tests.py
backend/heka/annotations/urls.py
backend/heka/annotations/views.py
backend/heka/docker-compose.yml
backend/heka/heka/settings.py
backend/heka/heka/urls.py
backend/heka/routers/AnnoRouter.py

This reverts commit 424d4018 and PR #538. It implements annotations endpoints. It creates a new database and connects to it.

Backend: Adds annotations to the heka-backend

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/App.js
heka-front/src/pages/SignUpPage/SignUpPage.js
heka-front/src/pages/SignUpVerificationPage/SignUpVerificationPage.css
heka-front/src/pages/SignUpVerificationPage/SignUpVerificationPage.js
heka-front/src/tests/ForgotPassword.test.js

I implemented email verification for both doctor and regular user sign up . Since backend team did not implemented email verification for sign up yet, I could not provide backend connection.  
After this functionality, users shall be able to verify their email addresses after filling sign form.  Users should follow following steps to register our system:
*  For regular users ( not doctor), => They should fill sign up form providing email, username, and password.
*  For doctors  => They should fill sign up form providing full name, institution name,  years of experience, branch, diploma, email, username and password.
*  After sign up form, email with verification code will be sent and users are directed to verifcaiton page that consist of input text for verification code and a button named …

Frontend: Email Verification for Sign Up

---

backend/heka/docker-compose.yml
backend/heka/textSearch/views.py

I fixed the bug about the count parameter. The error "int() argument must be a string, a bytes-like object or a real number, not 'NoneType'" was received when the count parameter was not supplied as input. I fixed the bug here with two different if condition checks I added. I also made changes in the format of the responses in the post search functionality.

Backend: Search Application - Bug fix about count parameter

---

heka-front/src/App.js
heka-front/src/components/Navbar/Navbar.js
heka-front/src/components/Post/Post.js
heka-front/src/pages/ProfilePage/ProfilePage.js

This PR adds the ability for users to view the profile page of the author of a post by clicking on the profile icon on the single post page.
* A dynamic route was created for the single post page, which includes a parameter for the unique identifier of the post.
* The profile icon for the author of the post was displayed on the single post page.
* The react-router-dom library was used to navigate to the profile page for the author when the profile icon was clicked. The route for the profile page is also dynamic and includes a parameter for the unique identifier of the author.
* The necessary data for the author was retrieved from the database using the unique identifier passed in the route, and the profile information for the author was displayed on the profile page.

Frontend: Single Profile Page with Dynamic URL

---

heka-mobile/app/src/main/res/layout/list_item_comment.xml

Line bug fixed, UI enhanced.
Also like-dislike buttons are right-centered.

Line bug fixed at comments, UI enhanced

---

backend/heka/posts/models.py
backend/heka/textSearch/urls.py
backend/heka/textSearch/views.py

I have added the sorting functionality for posts. From now on, users can sort posts by upvote count, comment count, create date and last update date. Below is the developed endpoint:
/api/search/sort?type={input}&count{input}
for sorting according to create date, last update date, comment count and upvote count: 
type = create_date
type = update_date
type = comment_count
type =  upvote_count
Besides that, with the help of the count parameter users can limit the number of post in the response.

Backend: Search Application - Added the sorting functionality for posts

---

backend/heka/textSearch/views.py

Response format updated according to the needs of the front end team.

Backend: Search Functionality - Update response format

---

heka-front/src/App.js
heka-front/src/api/Backend/Backend.js
heka-front/src/components/Navbar/Navbar.js
heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/components/TextAnnotation/TextAnnotation.js

I have implemented the text annotation structure using the Recogito library. This allows us to store and retrieve annotations made by users according to W3C standards, and to display them properly on the frontend of the application.
I have followed the implementation steps outlined in the issue description and have tested the integration to ensure that it is working correctly.

Frontend: Text Annotation Backend Connection 

---

heka-mobile/.idea/misc.xml
heka-mobile/app/src/main/AndroidManifest.xml
heka-mobile/app/src/main/java/com/bounswe/heka/data/AnnotationResponse.kt
heka-mobile/app/src/main/java/com/bounswe/heka/image/ImageViewModel.kt
heka-mobile/app/src/main/java/com/bounswe/heka/network/ApiService.kt
heka-mobile/app/src/main/java/com/bounswe/heka/post/FullPostFragment.kt
heka-mobile/app/src/main/java/com/bounswe/heka/post/FullPostViewModel.kt
heka-mobile/app/src/main/java/com/bounswe/heka/timeline/TimelineListItemState.kt
heka-mobile/app/src/main/res/layout/fragment_full_post.xml

https://github.com/bounswe/bounswe2022group4/issues/560

Heka mobile text annotation

---

heka-front/src/api/Backend/Backend.js
heka-front/src/components/SearchBar/SearchBar.js

In this PR, I implemented search functionality for posts with backend connection.   After users provide a keyword (can be number, or character), our system will return best 4 option matching entered search keyword.  Our system display results as a link to related post with title label.
After this functionality, users shall be able seach a post providing a keyword. 
**Users should follow following steps to search a post in our system:**
*   They should provide a keyword that is included in text or title of a post. 
*  After entering keyword,  matching results are dispalyed in order of best matching. If there are more than 4 posts, they can show title of the best 4 matching post. The reason of this is restriction on size of screen.
*  Users shall be able to click on a result to go to post …

Frontend : Search Functioanlity for Posts

---

heka-front/src/App.js
heka-front/src/components/Chat/MessageChat.js
heka-front/src/components/Comment/Comment.js
heka-front/src/components/CommentBox/CommentBox.js
heka-front/src/components/Navbar/Navbar.js
heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/EditProfilePage/EditProfilePage.js
heka-front/src/pages/HomePage/HomePage.js
heka-front/src/pages/PostPage/PostPage.js
heka-front/src/pages/ProfilePage/ProfilePage.js
heka-front/src/pages/SignInPage/SignInPage.js

I've implemented a solution to store the authentication token and user information in local storage when the user signs in, and delete it when the user signs out. This will allow us to persist the token and user information even after the page is refreshed or the tab is closed.
I've made the following changes:
1) Modified the SignInPage component to save the authentication token and user information to local storage when the user signs in.
2) Modified the App component to retrieve the token and user information from local storage when the page is refreshed or the tab is closed.
3) Modified the App component to delete the token and user information from local storage when the user signs out.
4) I've tested the implementation and everything seems to be working as expected. Please review and …

Frontend: Local Storage For Authentication Token and User Info

---

heka-front/src/pages/ProfilePage/ProfilePage.js
heka-front/src/tests/ProfilePage.test.js

I have added unit test cases for the profile page in this PR. I have covered key functionalities such as displaying the user's information. The test cases use the Jest to verify that the profile page is functioning correctly.
I have also added these test cases to the project's test suite, so they will be run every time the code is changed or the application is deployed.

Frontend: Profile Page Unit Test Cases

---

heka-front/src/pages/EditProfilePage/EditProfilePage.js
heka-front/src/pages/ProfilePage/ProfilePage.js
heka-front/src/tests/EditProfilePage.test.js
heka-front/src/tests/ProfilePage.test.js

I have added unit test cases for the edit profile page in this PR. I have covered key functionalities such as allowing the user to update their information and saving the changes. The test cases use the Jest to verify that the edit profile page is functioning correctly.
I have also added these test cases to the project's test suite, so they will be run every time the code is changed or the application is deployed.

Frontend: Edit Profile Page Unit Test Cases

---

heka-front/src/api/Backend/Backend.js
heka-front/src/components/SearchBar/SearchBar.js

In this PR, I implemented search functionality for users with backend connection.   After users provide a keyword (can be number, or character), our system will return best 4 option matching entered search keyword.  Our system display results as a link to related users with username label.
After this functionality, users shall be able seach a user providing a keyword. 
**Users should follow following steps to search a user in our system:**
*   They should provide a keyword that is included in username of a user. 
*  After entering keyword,  matching results are displayed in order of best matching. If there are more than 4 users, they can show usernames of the best 4 matching users. The reason of this is restriction on size of screen.
*  Users shall be able to click on a result to go to …

Frontend : Search Functioanlity for Users

---

heka-mobile/.idea/misc.xml
heka-mobile/app/src/main/java/com/bounswe/heka/data/SearchPostResponse.kt
heka-mobile/app/src/main/java/com/bounswe/heka/data/SearchUserResponse.kt
heka-mobile/app/src/main/java/com/bounswe/heka/home/HomeFragment.kt
heka-mobile/app/src/main/java/com/bounswe/heka/network/ApiService.kt
heka-mobile/app/src/main/java/com/bounswe/heka/search/SearchFragment.kt
heka-mobile/app/src/main/java/com/bounswe/heka/search/SearchManager.kt
heka-mobile/app/src/main/java/com/bounswe/heka/search/SearchResultAdapter.kt
heka-mobile/app/src/main/java/com/bounswe/heka/search/SearchViewModel.kt
heka-mobile/app/src/main/res/layout/fragment_search.xml
heka-mobile/app/src/main/res/layout/list_item_people_search.xml
heka-mobile/app/src/main/res/layout/list_item_post_search.xml
heka-mobile/app/src/main/res/layout/list_item_search_empty.xml
heka-mobile/app/src/main/res/layout/list_item_search_title.xml
heka-mobile/app/src/main/res/navigation/nav_graph.xml

https://github.com/bounswe/bounswe2022group4/issues/598

Heka mobile search

---

backend/heka/textSearch/views.py

There was a bug about the sorting logic, with this pr it will be removed.

Backend: Search Application - Bug fix about sort functionality

---

backend/heka/users/views.py

The message is updated to "Using this code, you can register to the application or reset your password."

Backend: Updated message contents of the email

---

heka-front/package-lock.json
heka-front/src/components/Comment/Comment.js
heka-front/src/components/CommentBox/CommentBox.js
heka-front/src/components/Post/Post.js
heka-front/src/components/PostBox/PostBox.js
heka-front/src/pages/SignUpPage/SignUpPage.js

**Pull Request Description:**
Implementation of the number of comments made to a post is done according to requirement 1.2.5.2. Users now can see how many comments are made to their or other users' posts without clicking the show comments button. Also, the number of comments is dynamic and changes immediately whenever a user submits a new comment.
You can see the related issue from the following link:
#542 
_**Reviewer:**_ @umutdenizsenerr 
**Review Deadline:**  26.12.2022 23.59

Frontend: Comment Number Display

---

heka-front/package-lock.json
heka-front/src/pages/SignUpPage/SignUpPage.js

I have added password check functionality for the signup page. This pull request completes the requirements of user authentication in our application. I have used the regex functionality to check whether the password satisfies the conditions or not.
I have made the changes in the SignUp.js file. Our sign-up process is completely covered.
You can see the related issue from the following link:
#577

Frontend: Password check functionality is added

---

heka-front/src/pages/SignUpPage/SignUpPage.js
heka-front/src/pages/SignUpVerificationPage/SignUpVerificationPage.js

In this PR, I implemented  backend connection of sign up verification. However, backend service of this feature was not completed fully. Therefore, I have used this backend service partially to be able to provide verification to our users.
**After this functionality, users shall be able verify their email address during sign up**
* After users provide required information to register and then click the submit button, they are directed to email verification page . 
* A verification code is sent to email address of user who want to register.  Email verification page contains a text input for the verificaiton code and a "verify" button.  
* The system will show a error message if users provide npn-valid code.
*  If users provide valid code sent to their email address, their registration …

Frontend: Sign Up Verification Backend Connection

---

heka-front/src/tests/SignUpVerification.test.js

I have implemented unit tests for email verification of the sign up . Thanks to tests, the possibility of malfunctioning due to non-valid email accounts(fake users) will be decreased.
I used @testing-library/react to impelement unit tests. 
* I tested whether verification page is rendered correctly
*  I tested whether verification button is clicked correctly
*  I tested whether form is submitted  correctly
*  I tested whether an warning message is displayed when the verification code is incorrect
* I tested whether users are directed to verification completion page when the verification code is correct
➡️ For more details, you can look at #616 
@umutdenizsenerr 
26.12.2022 23.59

Frontend: Unit Tests for Sign Up Verification

---

backend/heka/annotations/tests.py
backend/heka/annotations/views.py
backend/heka/docker-compose.test.yml
backend/heka/users/serializers.py
backend/heka/users/tests.py

Testing is an essential part of the software development lifecycle. I created unit tests for the annotations. I find out some edge cases that I still need to handle. In the progress of creating tests, I found these edge cases and fixed them. 
The endpoints I created tests for are as follows:
- GET request for the image annotation
- GET request for the image annotation by post_slug
- POST request for the image annotation by post_slug
- GET request for the text annotation
- GET request for the text annotation by post_slug
- POST request for the text annotation by post_slug

Backend: Unit Tests for annotations

---

backend/heka/posts/tests.py

It implements the unit test for the creation of posts. Please review it.

Backend: Implements unit test for creation of posts.

---

backend/heka/posts/tests.py

It implements the unit test for updating and deleting posts. Please review it.

Backend: Implements unit tests for update and delete post.

---

heka-front/package-lock.json
heka-front/package.json
heka-front/src/App.js
heka-front/src/components/ChatBot/ChatBot.js
heka-front/src/components/Navbar/Navbar.js
heka-front/src/pages/ChatBotPage/ChatBotPage.js

This pull request implements a chatbot for our medical experience sharing platform. The chatbot is implemented using the React library react-simple-chatbot, which was selected based on its feature set and compatibility with our web application.
User interaction scenarios have been created and tested to ensure that the chatbot provides appropriate responses to various inputs. The chatbot has also been integrated into our web application and properly rendered on the desired page.
Notes:
* Please review the code for the chatbot implementation, user interaction scenarios, and rendering.
* Make sure to thoroughly test the chatbot before merging this pull request.

Frontend: ChatBot Implementation

---

heka-front/src/components/Comment/Comment.js
heka-front/src/components/Post/Post.js

Comment highlighting according to the user types and post shadowing is added.

Frontend: Comment highlights are added and post shadow is added

---

heka-mobile/app/src/main/java/com/bounswe/heka/login/LoginFragment.kt
heka-mobile/app/src/main/java/com/bounswe/heka/login/LoginViewModel.kt
heka-mobile/app/src/main/java/com/bounswe/heka/network/SessionManager.kt
heka-mobile/app/src/main/java/com/bounswe/heka/post/CreatePostViewModel.kt
heka-mobile/app/src/main/java/com/bounswe/heka/post/EditPostFragment.kt
heka-mobile/app/src/main/java/com/bounswe/heka/post/EditPostViewModel.kt
heka-mobile/app/src/main/java/com/bounswe/heka/post/FullPostFragment.kt
heka-mobile/app/src/main/java/com/bounswe/heka/profile/ProfileFragment.kt
heka-mobile/app/src/main/java/com/bounswe/heka/timeline/TimeLineAdapter.kt
heka-mobile/app/src/main/res/layout/fragment_edit_post.xml
heka-mobile/app/src/main/res/values/strings.xml

Doctor change category of posts functionality added.

Mobile doctor functionality

---

heka-front/src/pages/SignUpVerificationPage/SignUpVerificationPage.js

The backend service for sign up has not implemented yet,  our system were using static verification code. After last configration, our system can send dynamic verificaiton code. However, there is no API to get this code.  I resolved this issue in front side of our application. Now, verificaiton page works fine.

Frontend Bug: Sign Up Verification Code 

---

heka-front/src/tests/Comment.test.js
heka-front/src/tests/CommentBox.test.js

**Description:**
As per the issue #627 , I have prepared unit test cases for the CommentBox and Comment components in React.
The test cases for the Comment and CommentBox components are tested that the components are rendered correctly and that  they are rendered with the correct props.
**Steps to reproduce:**
Run the test cases using a testing library, such as Jest
**Expected result:**
The test cases should pass, indicating that the Comment and CommentBox components are rendering correctly and with the correct props.
**Actual result:**
The test cases pass as expected.
@umutdenizsenerr 
**Deadline:** 27.12.2022 11.59 A.M

Frontend: Added Unit Tests for CommentBox and Comment Components

---

backend/heka/posts/tests.py

This implements unit tests for the following APIs.
- POST : *api/post/create-post* 
- POST : *api/post/update/\<slug>/*
- POST : *api/post/delete/\<slug>/* 
- GET   : *api/post/fetch/\<slug>/* 
- POST : */api/post/create-comment/{slug}* 
- POST : */api/post/update-comment/{slug}/{id}*  
- POST : */api/post/delete-comment/{slug}/{id}* 
- GET :   */api/post/fetch-comment/{slug}/{id}* 
- POST : */api/post/upvote-post/{slug}*  
- POST : */api/post/downvote-post/{slug}* 
- POST : */api/post/upvote-comment/{slug}/{id}*  
- POST : */api/post/downvote-comment/{slug}/{id}*  

Backend: Implements unit tests for Post and Comment APIs.
